### ISSUE TITLE
Translate bug

### ISSUE THREAD

**Issue by projct1** [azuyalabs/yasumi#121] opened 2018-12-02 22:32 UTC
Hello! I found strange bug! I make calendar!
Translate works only with first holiday: http://skrinshoter.ru/s/031218/qrfDahGR
In `Russia.php` provider all holidays are translated http://skrinshoter.ru/s/021218/7enYMBZO
Here is simplified code:
```php
$service = Yasumi::create('Russia', 2020, 'ru_RU');
$holidays = array_flip($service->getHolidayDates());
$period = new CarbonPeriod('2020-01-01', new CarbonInterval('P1D'), '2020-12-31');

foreach ($period as $month) {
    $date = $month->toDateString();

    if (array_key_exists($date, $holidays)) {
        echo $service->getHoliday($holidays[$date])->getName() . '<br>';
    }
}
```

**Comment by stelgenhof** [comment] 2018-12-03 01:41
I've tried using your example but it is incomplete. (For example `$this->holidayService` and `$date` are not defined).

Can you maybe provide a standalone working example? That way I can better understand the issue.

Thanks! Sacha

**Comment by projct1** [comment] 2018-12-03 11:00
@stelgenhof Yea, sry... I edited first message, all works standalone!

**Comment by stelgenhof** [comment] 2018-12-03 12:18
@projct1 Thanks! Much better :)
From what I can see, there is something wrong with the Russia Holiday Provider. Indeed only the first holiday is in the Russian language and the others not.

However if I try another country (e.g. Japan with the Japanese locale) then all holidays are translated correctly. Using your code with this change: `$service = Yasumi::create('Japan', 2020, 'ja_JP')` will render:

```
元日
成人の日
建国記念の日
春分の日
昭和の日
憲法記念日
みどりの日
こどもの日
振替休日 (憲法記念日)
海の日
体育の日
山の日
敬老の日
秋分の日
文化の日
勤労感謝の日
天皇誕生日
```

Not sure what the issue is, but let me investigate further.

Cheers! Sacha

**Comment by stelgenhof** [comment] 2018-12-03 12:36
@projct1 Found the issue already... Except New Years day, all holidays for Russia don't have the locale parameter in place, which is needed for translation. Without that, Yasumi will use the fallback locale of 'en_US'.

I will make a fix for this.

Thanks for spotting this one!

**Comment by projct1** [comment] 2018-12-03 12:54
@stelgenhof Thanks dude) How i can update package?

**Comment by stelgenhof** [comment] 2018-12-03 13:30
@projct1 It's not fixed yet...

**Comment by stelgenhof** [comment] 2018-12-04 00:38
Issue has been fixed in the 'develop' branch.

**Closed by stelgenhof** 2018-12-04 00:38 UTC
Labels: bug

**Comment by projct1** [comment] 2018-12-04 07:49
Ok, thanks =)
