### ISSUE TITLE
Missing Charles III Coronation in the UK

### ISSUE THREAD

**Issue by Jimbob001** [azuyalabs/yasumi#307] opened 2023-01-19 15:38 UTC
Missing an extra bank holiday in the UK I believe; 8th May 2023.

https://www.gov.uk/bank-holidays

**Comment by stelgenhof** [comment] 2023-01-31 14:20
Closing (Duplicate of https://github.com/azuyalabs/yasumi/pull/305)

**Closed by stelgenhof** 2023-01-31 14:20 UTC
